### ISSUE TITLE
Problems about `poseidon2_wide` in `recursion`

### ISSUE THREAD

**Issue by xiyu1984** [succinctlabs/sp1#1147]
In the tests of [/recursion/core/poseidon2_wide](https://github.com/succinctlabs/sp1/blob/main/recursion/core/src/poseidon2_wide/mod.rs#L183-L184), if we change any of the below to `0`, the test of [`poseidon2_wide_prove_babybear_success`](https://github.com/succinctlabs/sp1/blob/6be0efa16f8cc56a9c7a286fef71d8f0b51f2c62/recursion/core/src/poseidon2_wide/mod.rs#L315C8-L315C45) will fail.

```rs
const NUM_ABSORBS: usize = 1000;
const NUM_COMPRESSES: usize = 1000;
```

I think the two cases **SHOULD NOT** affect each other. However, if `NUM_ABSORBS` or `NUM_COMPRESSES` is set to `0`, the other case will be affected. So is there anything I missed?

- Here is the error message when `NUM_ABSORBS = 0; NUM_COMPRESSES = 1000`: 

![image](https://github.com/user-attachments/assets/d4d4f7bf-31e9-4e04-98ab-2e71d6f1d124)

- Error when `NUM_ABSORBS = 1000; NUM_COMPRESSES = 0`:

![image](https://github.com/user-attachments/assets/9e14acab-7b17-4f54-b821-634d5e2fba2c)

**Comment by kevjue** [comment]
Hi @xiyu1984 - This is intended behavior.  The `poseidon2_wide` AIR requires that there is at least one `compress` and one `hash` invocation in the recursion program.   This made the constraints simpler and is a safe assumption to make, since many compresses and hashes will be needed to verify SP1's plonky3/fri based proofs.
