### ISSUE TITLE
Implement an optimized SP1 Serializer

### ISSUE THREAD

**Issue by puma314** [succinctlabs/sp1#724]
Right now, when a user does `sp1_zkvm::io::read::<T>(...)`, underneath the hood we use `bincode` as our serializer to read from the buffer. Reference is [here](https://github.com/succinctlabs/sp1/blob/2f57e1e77f7c88396b571bd961d3cbe4b1291c7a/core/src/io.rs#L48).

However using `bincode` as a serializer is inefficient, since we don't want any compression and we don't want to pay zkVM cycles for reading in data. 

We should implement our own optimized zkVM serializer that just serializes/deserializes data ideally in `u32` aligned chunks.

**Comment by malik672** [comment]
@puma314 assign this to me

**Comment by drcapybara** [comment]
# Comparison of deserialization strategies

## Summary

During our performance testing and benchmarking of deserialization processes, we observed a consistent minimum of approximately 4.6 million x86 cycles consumed when using rkyv, regardless of the data size. We compare this with bincode results and explore the performance of a pointer cast operation.

## Details

In our benchmarks using the rkyv and bincode libraries for deserialization, we've noted that the number of cycles consumed with rkyv does not scale with data size, showing a fixed minimum cycle count suggestive of zero-copy deserialization mechanics.

## Cycle Count Comparison

The following table summarizes the cycle counts observed for deserialization using transmute, rkyv, and bincode across various data sizes:

| Data Size    | transmute  | rkyv   | bincode    |
|--------------|------------------|--------------|------------------|
| Small (100KB) | 607              | 4,741,032    | 18,479,850       |
| Medium (5MB)  | 548              | 4,990,638    | 681,913,198      |
| Large (50MB)  | 762              | 4,638,140    | 6,730,678,512    |

### Interpretation

- **Transmute**: Shows minimal cycle counts across all data sizes, indicating a highly efficient direct memory mapping process.
- **rkyv**: Displays consistent cycle counts around 4.6 million, supporting the hypothesis of a fixed minimum cycle count due to zero-copy mechanics.
- **bincode**: Cycle counts increase significantly with data size, indicating less efficiency for larger datasets.

## Additional Findings: Pointer-Cast Deserialization

In another series of tests, deserializing data via a simple pointer cast to a struct with no heap-allocated data, we observed a dramatically reduced cycle count of roughly 600 cycles per 100,000 bytes, for the following simple struct:

```rust
#[derive(Debug)]
struct TestStruct {
    int: u8,
    string: [u8; 24],    // Mocking a fixed-size array instead of a String
    data: [u8; 100_000], // Mocking a fixed-size array instead of a Vec<u8>
}
```

 This method is highly efficient but limited to scenarios where data structures are compatible with direct memory mapping. Despite also being cartoonishly dangerous, the prospect of completely zero-cost deserialzation in the zkVM may be an avenue worth exploring. See [this](https://l2ivresearch.substack.com/p/tech-deep-dive-verifying-fhe-in-risc) for further reading and exploration of this technique.

Further, the ```include_bytes_aligned!``` [macro](https://docs.rs/include_bytes_aligned/latest/include_bytes_aligned/)  may also satisfy the requirement to read machine words with u32 alignment from bytes embedded within the RISCV binary.

## Efficiency Considerations for Smaller Datasets

While rkyv demonstrates excellent efficiency for large datasets with its low and consistent cycle count, it's important to note that bincode may be more efficient for scenarios where deserialization consumes less than ~4.6 million cycles. This is particularly relevant for smaller types where the overhead of rkyv's zero-copy mechanics does not offset its benefits.

### Proposed Strategy

Given the differences in performance characteristics, a possible strategy is to offer different ways to read and write data into the zkVM, best suited for the task at hand:
- **Use bincode** for smaller types and data where the lower absolute number of cycles leads to faster operations.
- **Use rkyv** for larger types and data or applications

This approach allows users to optimize their applications by selecting the most appropriate serialization method, potentially improving performance and efficiency across various use cases.

## References

- [rkyv Documentation](https://docs.rs/rkyv/latest/rkyv/)
- [bincode Documentation](https://docs.rs/bincode)

**Comment by matthiasgoergens** [comment]
Could you please share the source of the programs you used for benchmarking?

From what I can see, this looks like rkyv is faster?  But it also looks like this issue was closed without any further action?

Why does this issue talk about only bincode and rkyv in the first place?  It looks like `sp1_zkvm::io::read` uses serde, not bincode?  How does serde compare?

**Comment by Dustin-Ray** [comment]
> Could you please share the source of the programs you used for benchmarking?

I did this awhile ago, heres the approximate test I ran:

```rust
use core::arch::x86_64::_rdtsc;
use bincode;
use rand::Rng;

fn main() {
    // Generate 50MB of random data to deserialize
    let data: Vec<u8> = (0..50 * 1024 * 1024).map(|_| rand::random()).collect();

    // Start cycle count
    let start = unsafe { _rdtsc() };

    // Deserialization or other specific workload
    let _: Result<Vec<u8>, _> = bincode::deserialize(&data);

    // End cycle count
    let end = unsafe { _rdtsc() };

    // Calculate and print the difference in cycles
    let cycles = end - start;
    println!("Cycles: {}", cycles);
}
```

> From what I can see, this looks like rkyv is faster? 

rkyv appears to incur a flat cost, regardless of any size of data to deserialize. There may be "less safe modes" with even lower cycle costs.

> But it also looks like this issue was closed without any further action?

Not sure on that, I didnt ask to close it. Maybe this item is no longer a priority. It would be nice from a developers perspective to select either a "safe" or "unsafe" deserialization mode. Unsafe mode could embed the bytes to deserialize directly in the riscv binary then spend little to no cycles on a pointer cast to "deserialize". The tradeoff is a potentially much larger binary but a much lower computational burden.

Cryptographically, if we assume that the verifier is the party that constructs the binary, then there is no tractable means for the prover to cheat by deserializing bad data, because the only data it has access to has been embedded in the provable binary. The prover cannot argue that they used the correct bytes and still generate a proof that the verifier will accept, because the proof is obtained over the binary (at least in RISC-Zero, I actually havent audited this in SP1 )


> Why does the benchmark count x86 cycles?

Because that was the easiest way to run the experiment. I dont think we need to be terribly concerned with the cycle count difference for a specific architecture, rather I wanted to understand the computational costs of zero-copy vs copy deserialization. The results suggest bincode copies data during serialization, and we found a measurement of the cost of this. It shouldnt matter too much which arch this runs on. Running this on RISC-V for example, does not magically make the current configuration of bincode zero copy. (unless it does, then 1. wow and 2. my definition of magic should change)


## FInal note
RISC-Zero, the state of the art, is also not zero-copy, and as far as Im aware this is true for all major zkmvs. This is a surprising choice for zkvms in general because deserialization is a huge cost incurred in the proof process, in come cases dominating the cycle count by wide margins. Given that there isnt anything inherently unsafe if all the prover has access to is the binary with embedded bytes, and that binary is the public input to the STARK, I cant come up with an attack scenario that somehow allows the prover to break security of the proof by using a zero-copy deserializer. That doesnt mean an attack vector doesnt exist that I dont know of, or maybe SP1 is configured in a way where it only argues integrity of some parts of the binary, but not others.

This is a pretty simple and highly impactful improvement that could drastically change the performance of the vm, so not sure why it hasnt been pursued.

**Comment by matthiasgoergens** [comment]
@Dustin-Ray Thanks for the detailed write-up!

Btw, I recently had occasion to look into Risc-Zero's code.  I wouldn't exactly call them state of the art.  They have lots of questionable design and implementation choices.  (Eg as far as I can tell they support self-modifying code.  Something that's basically only used by malware and exploits, not anything any guest program developer would like to make easier.  To support that, they need to do the decoding inside of their zero knowledge proof.

Related to that, Risc-Zero also ignores flags in the ELF that mark certain sections as read-only.  Specifically, almost any sane modern system only allows either execution or writing for a specific part of memory, but never both.  Risc-Zero ignores that.)

**Comment by Dustin-Ray** [comment]
> They have lots of questionable design and implementation choices.

If thats true, and it hasnt been done yet, you might find yourself in a position to write that up in a paper formally (I would happily collaborate on that with you :) ) , I think that there is a gap in security analyses of ZKVMs across the board that badly needs to be filled.

> Btw, I'm a bit surprised that you got such a high (but flat) cycle cost from rkyv.

Yes I agree, the count seemed quite high at first, but for large deserializations, this number seemed less dramatic I suppose, which is why I made the comment about possibly just sticking with serde up to a certain point. In my own experiences however, I have found that if we are ok with unsafe rust, then you can simply pointer cast any size data for basically no cost at all, and keep an extremely lean implementation that has no reliance on external libraries and uses simple no_std rust. This only really works for simple primitive types in my experience though, anything in non-contiguous memory needs a more sophisticated deserialization strategy, which rkyv probably supplies, and might lead to a higher cycle count? Thats my hypothesis anyways.

> Did you use the 'access' or 'deserialize' functions? Only the former is zero-copy.

I dont recall off the top of my head, I dont have the implementation with me anymore. I want to say that `deserialize` sounds familiar. Like I said earlier, I only tried one solution, and I suspect there are probably cheaper methods of leveraging rkyv or some other libraries out there.
